### ISSUE TITLE
USG version

### ISSUE THREAD

**Issue by smvicente** [chrisstaite/DoTe#13]
Hi! first of all, thank you for this, I think it is a great solution!

I was wondering if it would be possible to compile it also for the USG. Currently the USG also uses EdgeOS, but the OpenSSL version is 1.0.1t, so when executing it, it can't locate the correct library: `error while loading shared libraries: libssl.so.1.1`

I could do it myself but I'm unsure on how to install cmake and the c++ compiler into the USG.

Thank you in advance!

**Comment by chrisstaite** [comment]
The compilation is performed through cross-compiling.  See .travis-ci.sh for how it's done.  It currently builds against debian stretch, do you know which version of debian the USG is based off?

**Comment by chrisstaite** [comment]
If it's based off wheezy, that mirror is no longer available: https://github.com/chrisstaite/DoTe/commit/18b305d2b21449704e5e9cee1c185c8ff77d9bfd

**Comment by smvicente** [comment]
For what I could gather, I think the USG is still running on EdgeOS 1.X, so based on Debian Wheezy :(

**Comment by chrisstaite** [comment]
That's an unsupported OS now, compiling for it would require bespoke mirrors.
