### ISSUE TITLE
Issues with running on EdgeRouter X

### ISSUE THREAD

**Issue by svandive** [chrisstaite/DoTe#18]
Good Day,

I have downloaded the most recent version from 10/31/2022 and followed along the installation instructions, however I am receiving an issue that I think means the binary is not compiled for my EdgeRouter's MIPs CPU ISA.  

```
root@ERX:/config/scripts# sudo /config/scripts/post-config.d/10-dote
/config/scripts/post-config.d/10-dote: line 2: /config/scripts/dote_mips: cannot execute binary file: Exec format error
```
Any suggestions?  I am running the version that says it is compiled for MIPs CPUs.  

```
Linux ERX 4.14.54-UBNT #1 SMP Thu Jun 15 09:00:10 UTC 2023 mips GNU/Linux
```

Thank You!!

**Comment by svandive** [comment]
Running 'file' on the binary produces this output:

```
root@ERX:/config/scripts/post-config.d# file /config/dote_mips 
/config/dote_mips: ELF 32-bit MSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 3.2.0, BuildID[sha1]=00dcad4d34144a1776c25e1f19a40064d95b97d1, stripped
```

Looking at this a bit closer it looks like the dote binary is compiled for MSB vs LSB.  When I run the 'file' command on '/bin/bash' I see it is compiled for LSB.

**Comment by svandive** [comment]
I have tried the dote_mips on an EdgeRouter 4 and it's working just fine on this platform (MIPS64).  I think I'll just move everything over to this Router.

**Comment by chrisstaite** [comment]
It's been a while, but there was something about ER-X platform that means I couldn't build for it, I don't remember the details now unfortunately. Pleased you managed to get it to work on ER-4.
